/**
 * LocalEffects.java
 * 
 * Created on 21.03.2010
 */

package net.slightlymagic.laterna.magica.effect;


import java.util.Set;

import net.slightlymagic.laterna.magica.GameContent;
import net.slightlymagic.laterna.magica.MagicObject;
import net.slightlymagic.laterna.magica.effect.characteristic.CharacteristicEffect;



/**
 * The class LocalEffects. A {@link MagicObject} has exactly one LocalEffects-Object, which stores all active local
 * continuous effects. A local effect is one not generated by a static ability, therefore being locked in after
 * created.
 * 
 * The spell or ability makes sure that the effect is in the LocalEffects as long as the effect should apply.
 * 
 * @version V0.0 21.03.2010
 * @author Clemens Koza
 */
public interface LocalEffects extends GameContent {
    /**
     * Returns the characteristic effects that currently apply to the object.
     * 
     * This set only contains the effects not from static abilities. In other words, effects for which the affected
     * objects not may change after the effect was created.
     * 
     * A spell or ability must store its effects, so that it can remove them when it stops to apply. Because
     * duplicate keys are not possible, effects can not be shared between multiple abilities, not even between
     * different instances of the same ability!
     * 
     * The returned set is not modifiable.
     */
    public Set<CharacteristicEffect> getEffects();
    
    /**
     * Adds the specified effect to the set.
     */
    public void add(CharacteristicEffect effect);
    
    /**
     * Removes the specified effect from the set.
     */
    public void remove(CharacteristicEffect effect);
}
